import type { NextPage } from "next";
import Head from "next/head";
import MysteryColor from "../components/MysteryColor/";
import Navbar from "../components/Navbar";
import TextField from "../components/TextField/";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";
import { useAppDispatch, useAppSelector } from "../app/hooks";
import AnswerColor from "../components/AnswerColor";
import { setLanguage, setTheme, skip } from "../redux/meta/metaSlice";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Collapse from "@mui/material/Collapse";
import ListColor from "../components/ListColor";
import ListLevel from "../components/ListLevel";
import DICT from "../utils/DICT";

const Home: NextPage = () => {
	const router = useRouter();
	const dispatch = useAppDispatch();
	const done = useAppSelector((state) => state.meta.done);
	const win = useAppSelector((state) => state.meta.win);
	const showList = useAppSelector((state) => state.meta.showList);
	const score = useAppSelector((state) => state.meta.score);
	const lang = useAppSelector((state) => state.meta.language);
	useEffect(() => {
		dispatch(skip());
	}, [dispatch]);
	useEffect(() => {
		const localMode = window.localStorage.getItem("mode");
		if (localMode === "light" || localMode === "dark") dispatch(setTheme(localMode));
	}, [dispatch]);
	useEffect(() => {
		const locale = router.locale;
		if (!locale) return;
		dispatch(setLanguage(locale));
	}, [dispatch, router]);
	return (
		<>
			<Head>
				<title>Colors</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Container maxWidth="md" sx={{ marginBlock: "2rem" }}>
				<Collapse in={!showList}>
					<Stack sx={{ width: "100%" }} gap="20px" alignItems="center">
						<Typography>
							{DICT.SCORE[lang]}: {score}
						</Typography>
						<MysteryColor />
						<TextField />
						{done && !win && <AnswerColor />}
					</Stack>
				</Collapse>
				<Collapse in={showList}>
					<Stack direction="row" gap="5px" sx={{ display: { xs: "none", sm: "flex" } }}>
						<ListLevel />
						<ListColor />
					</Stack>
					<Stack gap="5px" sx={{ display: { xs: "flex", sm: "none" } }}>
						<ListLevel />
						<ListColor />
					</Stack>
				</Collapse>
			</Container>
			<footer>
				<Typography fontSize={12}>Made with ❤️ in Bandung © 2022 Muhammad Ali Syaifudin</Typography>
			</footer>
		</>
	);
};

export default Home;
