import type { NextPage } from "next";
import Head from "next/head";
import MysteryColor from "../components/MysteryColor/";
import Navbar from "../components/Navbar";
import TextField from "../components/TextField/";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Colors</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Container maxWidth="xs" sx={{ pt: "10vh", pb: "10vh" }}>
				<MysteryColor />
				<TextField />
			</Container>
			<footer>
				<Typography fontSize={12}>Made with ❤️ in Bandung © 2022 Muhammad Ali Syaifudin</Typography>
			</footer>
		</>
	);
};

export default Home;
