import type { NextPage } from "next";
import Head from "next/head";
import MysteryColor from "../components/MysteryColor/";
import Navbar from "../components/Navbar";
import TextField from "../components/TextField/";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";
import { useAppDispatch, useAppSelector } from "../app/hooks";
import AnswerColor from "../components/AnswerColor";
import { setLanguage, setTheme } from "../redux/meta/metaSlice";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
	const router = useRouter();
	const dispatch = useAppDispatch();
	const done = useAppSelector((state) => state.meta.done);
	useEffect(() => {
		const localMode = window.localStorage.getItem("mode");
		if (localMode === "light" || localMode === "dark") dispatch(setTheme(localMode));
	}, [dispatch]);
	useEffect(() => {
		const locale = router.locale;
		if (!locale) return;
		dispatch(setLanguage(locale));
	}, [dispatch, router]);
	return (
		<>
			<Head>
				<title>Colors</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Container maxWidth="xs" sx={{marginBlock: "2rem"}}>
				<Stack sx={{ pt: "10vh", width: "100%" }} gap="20px" alignItems="center">
					<MysteryColor />
					<TextField />
					{done && <AnswerColor />}
				</Stack>
			</Container>
			<footer>
				<Typography fontSize={12}>Made with ❤️ in Bandung © 2022 Muhammad Ali Syaifudin</Typography>
			</footer>
		</>
	);
};

export default Home;
